public with sharing class FPAC_NCT_WhipMarketForecast {
	
	//public string UnitOfMeasurePoundCount {get; set;}
	//public string GraduatedPrice {get; set;}
    //public string InsurableIndicator {get; set;}
    //public string GrazingDays {get; set;}
    //public string AcresPerAnimalUnit {get; set;}
    //public string ApplicationClosingDate {get; set;}
    //public string NormalHarvestDate {get; set;}
    //public string FinalPlantingDate {get; set;}
    //public string AcreageReportingDate {get; set;}
	//public string DirectMarketPrice {get; set;}
	//public string ServiceCenterApproval {get; set;}
    //public string StateApproval {get; set;}
    //public string NatinalApproval {get; set;}
	//public string CountyDisasterYieldA {get; set;}
    //public string CountyDisasterYieldB {get; set;}
	
	
	public string StateCode {get; set;}
    public string CountyCode {get; set;}
	public string CropCode {get; set;}
    public string ProgramYear {get; set;}
    public string PayCrop {get; set;}
    public string PayType {get; set;}
    public string CropType {get; set;}
    public string CropIntendedUse {get; set;}
    public string PracticeCode {get; set;}
    public string PlantingPeriod {get; set;}
    public string CrushingDistrict {get; set;}
    public string UnitOfMeasureCode {get; set;}
    public string PreventedFactor {get; set;}
    public string UnharvestedFactor {get; set;}
    public string OrganicCertifiedFactor {get; set;}
    public string OrganicTransitionalFactor {get; set;}
    public string MarketPrice {get; set;}
    public string OrganicMarketPrice {get; set;}
    public string CalculatedYield {get; set;}
    public string WhipPayCrop {get; set;}
    public string WhipPayType  {get; set;}
    public string TreeBushVineDamagerFactorI {get; set;}
    public string TreeBushVineDamagerFactorII {get; set;}
    public string TreeBushVineDamagerFactorIII {get; set;}
    public string TreeBushVinePriceI {get; set;}
    public string TreeBushVinePriceII {get; set;}
    public string TreeBushVinePriceIII {get; set;}
}