public with sharing class FPAC_NAP_Production {
	public string FinalIntendedUseCode {get; set;}
    public string StageCode  {get; set;}
	public string UnitOfMeasureCode  {get; set;}
	public string Quantity  {get; set;}
	public string UncountedQuantity  {get; set;}
	public string CorrectionQuantity  {get; set;}
	public string CorrectionTypeCode  {get; set;}
	public string CrushingDistrict {get; set;}
}