public class FPAC_SCIMS_OtherProducer {
    public string CoreCustomerId {get; set;}
	public string InactiveCustomer	{get; set;}
	public string CwExceptionCode {get; set;}
	public string HelExceptionCode {get; set;}
	public string PcwExceptionCode {get; set;}
    public FPAC_SCIMS_RepCapTractAuthorization RepCapTractAuthorization {get; set;}
	public FPAC_SCIMS_RepCapTractAuthorization RepCapFieldAuthorization {get; set;}
}